"""init

Revision ID: 21e83bf57583
Revises: 
Create Date: 2025-07-16 09:32:15.979958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21e83bf57583'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.CHAR(length=50), nullable=False),
    sa.Column('email', sa.CHAR(length=100), nullable=False),
    sa.Column('phone_number', sa.CHAR(length=11), nullable=False),
    sa.Column('hashed_password', sa.CHAR(length=200), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('last_modified_ts', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('password_reset_token', sa.CHAR(length=100), nullable=True),
    sa.Column('reset_token_expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='testing'
    )
    op.create_index(op.f('ix_testing_user_email'), 'user', ['email'], unique=True, schema='testing')
    op.create_index(op.f('ix_testing_user_id'), 'user', ['id'], unique=False, schema='testing')
    op.create_index(op.f('ix_testing_user_phone_number'), 'user', ['phone_number'], unique=True, schema='testing')
    op.create_index(op.f('ix_testing_user_username'), 'user', ['username'], unique=True, schema='testing')
    op.create_table('chat_session',
    sa.Column('chat_session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.TEXT(), server_default='Chat Session', nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.Column('last_modified_ts', sa.DateTime(), server_default=sa.text("timezone('UTC', now())"), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['testing.user.id'], ),
    sa.PrimaryKeyConstraint('chat_session_id'),
    schema='testing'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_session', schema='testing')
    op.drop_index(op.f('ix_testing_user_username'), table_name='user', schema='testing')
    op.drop_index(op.f('ix_testing_user_phone_number'), table_name='user', schema='testing')
    op.drop_index(op.f('ix_testing_user_id'), table_name='user', schema='testing')
    op.drop_index(op.f('ix_testing_user_email'), table_name='user', schema='testing')
    op.drop_table('user', schema='testing')
    # ### end Alembic commands ###
